### ISSUE TITLE
🐛 Bug: Improve behaviour of Draft 2020-12 for mobile devices

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#483] opened 2024-03-08 17:35 UTC
### Describe the bug

The page with the release notes for draft 2020-12: https://json-schema.org/draft/2020-12/release-notes does not work well for mobile devices. The hold school tables producing a huge horizontal overflow. 

<img width="380" alt="Screenshot 2024-03-08 at 18 34 38" src="https://github.com/json-schema-org/website/assets/40007659/a14ebe76-45be-479f-a887-92cb3081424c">

### Steps To Reproduce

1. Go to https://json-schema.org/draft/2020-12/release-notes
2. Use developer tools to navigate like a mobile 
3. Check the unnecessary horizontal overflow 

### Expected Behavior

The ideal solution for me is a grid that when it reaches the breaking point converts that 1 row x 2 columns approach into a 2 rows x 1 column so we avoid the overflow to happen. 

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by DhairyaMajmudar** [comment] 2024-03-08 17:42
@benjagm Shall I take this up : D

**Comment by Adity20** [comment] 2024-03-08 18:02
@benjagm I test the changes the code was working fine for these components what extra you're looking forward to here

**Comment by DhairyaMajmudar** [comment] 2024-03-08 18:05
Actually the website page is getting overflow in x direction which needed to be fixed.

**Comment by Adity20** [comment] 2024-03-08 18:07
I fixed that issue too or maybe it will get fixed once the changes are applied to all the components.

**Comment by Adity20** [comment] 2024-03-08 18:08
@benjagm I was going to fix this overflow issue too 
So if it's fine for you I can work on this too as I know what changes need to be made for this

**Comment by VivekJaiswal18** [comment] 2024-03-08 20:39
@benjagm Can I work on this issue!

**Comment by ayushtiwari110** [comment] 2024-03-08 21:40
Hi there @benjagm !, I tried reproducing the bug but seems like the page isn't available on the production link. It's showing a 404 error.

**Comment by AdityaSingh-02** [comment] 2024-03-09 04:09
@benjagm Can you please assign me this issue

**Comment by DhairyaMajmudar** [comment] 2024-03-09 04:39
Also while inspecting the bug it was found that this buggy behaviour is visible in all the pages of specifications section.

**Comment by Adity20** [comment] 2024-03-09 04:51
Yeah this is due to two different components for styling one jsonEditor and one styledMarkdown.

**Comment by Sahil-Shadwal** [comment] 2024-03-09 10:22
I would like to work on this issue. I looked into it and the li and th is the major reason for that overflow if we make that responsive it will solve the whole issue.

**Comment by benjagm** [comment] 2024-03-09 11:54
@Adity20 is fixing the problems with the code editor.

> Hi there @benjagm !, I tried reproducing the bug but seems like the page isn't available on the production link. It's showing a 404 error.

Please try https://json-schema.org/draft/2020-12/release-notes

**Comment by benjagm** [comment] 2024-03-09 11:56
@Adity20 is working on aligning the code components.

This issue is just to change the tables behaviour for mobile in the  the page 2020-12/release-notes. @AdityaSingh-02 please go ahead with this one.

**Closed** 2024-03-11 10:48 UTC
Labels: 🐛 Bug, Status: In Progress
