### ISSUE TITLE
[docs]: Inconsistent code rendering in documentation examples

### ISSUE THREAD

**Issue by DarhkVoyd** [json-schema-org/website#349] opened 2024-02-24 03:52 UTC
#### Describe the bug

While navigating through the getting started docs, I observed a formatting inconsistency in the examples. When the code snippet is the entire piece of code, it is properly rendered with colors and indentations. However, in cases where the code is only a part of the entire example and is denoted by "..." to indicate existing code, it appears as plain text without proper formatting.

#### How to Reproduce

1. Navigate to the getting started documentation.
2. Look for examples using "..." to denote existing code snippets.
3. Notice that these snippets are rendered as plain text without colors or indentations.

#### Screenshot
![Screenshot 2024-02-23 at 10 33 46 PM](https://github.com/json-schema-org/website/assets/77478658/57ae4e12-125a-45ce-b6d6-1bfa82fe1a6e)

#### Expected behavior

I expect that all code snippets, whether part of the entire example or not, should be consistently rendered with proper code formatting, including colors and indentations.

**Comment by Sahil-Shadwal** [comment] 2024-02-24 07:07
Please assign me this issue , Thanks.

**Comment by DarhkVoyd** [comment] 2024-02-24 07:27
Hey @Sahil-Shadwal 
This issue is currently is in `triage`. Kindly wait till a maintainer marks it `available`.

**Comment by benjagm** [comment] 2024-02-24 08:17
Expectation with this issue is format the json code properly if it is not formatted and if possible show "json" instead of "data".

**Comment by benjagm** [comment] 2024-02-24 08:21
The issue is ready. @DarhkVoyd are you ok with @Sahil-Shadwal fixing this and you be the reviewer?

**Comment by DarhkVoyd** [comment] 2024-02-24 09:14
@benjagm Yeah, sure!

**Comment by benjagm** [comment] 2024-02-24 09:23
All yours @Sahil-Shadwal! Please go ahead!

**Comment by benjagm** [comment] 2024-03-05 15:39
@Sahil-Shadwal are you still working on it?

**Comment by Adity20** [comment] 2024-03-05 16:08
Okay @benjagm

**Comment by Sahil-Shadwal** [comment] 2024-03-06 13:24
hey @benjagm, i am in mid of my exams right now . So if you want you can assign this issue to someone else. I hope this won't leave a bad impression . Will be looking forward to contribute in another issue.

**Comment by DhairyaMajmudar** [comment] 2024-03-06 13:28
If it's okay shall I continue this one : )

**Comment by benjagm** [comment] 2024-03-06 13:30
@Sahil-Shadwal not a bad impression at all!! We hope you exams go well. That is the priority right now. Good luck!

@DhairyaMajmudar will fix this one. And as soon as you are done with the exams just let me know if you can find issues to complete your qualification task.

**Comment by benjagm** [comment] 2024-03-06 13:32
Dhairya, please use jsonc instead of json as type for those cases with "..."

**Comment by DhairyaMajmudar** [comment] 2024-03-06 13:32
All the best Sahil for exams 💯

**Comment by DhairyaMajmudar** [comment] 2024-03-06 13:32
> Dhairya, please use jsonc instead of json as type for those cases with "..."

Sure I will have a look on this.

**Comment by Adity20** [comment] 2024-03-06 13:33
@benjagm this issue is related to  issue #456 and I am working on that one so maybe the similar solution will be applied to this one.

**Closed** 2024-03-08 14:34 UTC
Labels: 🐛 Bug, Status: In Progress

**Comment by Sahil-Shadwal** [comment] 2024-03-11 04:07
> Sahil-Shadwal not a bad impression at all!! We hope you exams go well. That is the priority right now. Good luck!
> 
> DhairyaMajmudar will fix this one. And as soon as you are done with the exams just let me know if you can find issues to complete your qualification task.

Hey @benjagm i would like to take you on your words, what should i do to complete my qualification tasks cause there is not any issues to work on. 
I do have worked on few bowtie issues:
Fixes https://github.com/bowtie-json-schema/bowtie/issues/935
Fixes https://github.com/bowtie-json-schema/bowtie/issues/973
