### ISSUE TITLE
Multiple Hydratation errors

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#389] opened 2024-02-28 18:50 UTC
#### Describe the bug
The website has multiple hydration issues originating from different sections in Layout and Sidebar components due to client side changes on server components mostly related to fragment identifiers. This is visible in the production deployed website as minified errors in dev tools. Take a look: https://json-schema.org/learn/getting-started-step-by-step#overview

<img width="983" alt="Screenshot 2024-02-28 at 19 47 48" src="https://github.com/json-schema-org/website/assets/40007659/0893e6b3-79da-4953-a336-948c82bd1bce">

#### Expected behavior
We need to fix this ASAP to reduce friction in our users.

**Comment by vishisht-dubey** [comment] 2024-02-28 18:51
hey @benjagm can i solve this?? please assign this to me

**Comment by benjagm** [comment] 2024-02-28 18:54
Sure think @vishisht-dubey ! Thanks a lot for stepping in! Issue assigned to you!

**Comment by vishisht-dubey** [comment] 2024-02-28 20:41
@benjagm I have faced this type of issue i think this happens because of useRouter hook from next/router, i guess we should use useRouter from next/navigation what's your opinion??

**Comment by DhairyaMajmudar** [comment] 2024-02-29 04:57
Hi @vishisht-dubey importing `useRouter` from `next/navigation` is required when the next application is app router, but here we are using pages router so no to do this. Also, hydration errors take place when text content does not match server-rendered HTML.

**Comment by DhairyaMajmudar** [comment] 2024-02-29 04:57
if you need any other help feel free to ask : )

**Comment by Adity20** [comment] 2024-02-29 05:16
@DhairyaMajmudar Can you elaborate this a little how can one match the text content.

**Comment by DhairyaMajmudar** [comment] 2024-02-29 05:32
You have to check if any irrelevant tag is not bonded by others tags , you can know more about this from here [link](https://nextjs.org/docs/messages/react-hydration-error)

**Comment by vishisht-dubey** [comment] 2024-02-29 05:50
> You have to check if any irrelevant tag is not bonded by others tags , you can know more about this from here [link](https://nextjs.org/docs/messages/react-hydration-error)

yes i was also thinking of the same

**Comment by vishisht-dubey** [comment] 2024-02-29 12:56
@DhairyaMajmudar @benjagm i feel that the error was beacuse of some eslint rules and i also think that those rules are not necessary for the project, i have specified use client in some places for removing the bug and also removed some eslint rules, i am creating a pr please let me know if there are any changes

**Comment by benjagm** [comment] 2024-03-01 08:56
Let's fix this. Not sure if this is because eslint @aialok thoughts?

**Comment by DhairyaMajmudar** [comment] 2024-03-01 08:57
I can help in this if required : )

**Comment by benjagm** [comment] 2024-03-01 09:01
@DhairyaMajmudar @vishisht-dubey can you pair to fix this issue together?

**Comment by aialok** [comment] 2024-03-01 09:07
> Let's fix this. Not sure if this is because eslint @aialok thoughts?

Nope, this is not eslint problem.

Checkout this for more details https://stackoverflow.com/questions/71706064/react-18-hydration-failed-because-the-initial-ui-does-not-match-what-was-render

**Comment by vishisht-dubey** [comment] 2024-03-01 09:42
@benjagm @aialok yes i got it not because of eslint but something else also the build is also failing which means that there is some other issue 
@DhairyaMajmudar any thoughts?

**Comment by DarhkVoyd** [comment] 2024-03-01 10:44
Hey, apologies for being late to the discussion. I stumbled upon these errors while working with another contributor on their PR. These errors originate mostly from `router.asPath` method in the mentioned components.

**Comment by vishisht-dubey** [comment] 2024-03-01 10:49
Hii @DarhkVoyd I think what happens is when it tries to fetch that string after # so I guess it is not getting it correctly because of which when we paas it as an id it didn't matches and throws hydration error
Am I right??

**Comment by DarhkVoyd** [comment] 2024-03-01 10:54
I do not understand your question completely. 
My understanding is, when the server resolves asPath, it is 
`https://json-schema.org/learn/getting-started-step-by-step` 
whereas during hydration when the client resolves asPath, it is 
`https://json-schema.org/learn/getting-started-step-by-step#overview`

**Comment by DarhkVoyd** [comment] 2024-03-01 11:02
One such issues this leads to is the resolution of Tailwind classes that are applied to certain components.

**Comment by vishisht-dubey** [comment] 2024-03-01 11:04
So I should approach it like changing the tailwind classes for let's say that overview class and in the url we should not pass that #overview?

**Comment by DarhkVoyd** [comment] 2024-03-01 11:09
We shouldn't change the classes or the url because they are responsible for certain features that we need. As per my understanding, the best idea probably to simply make sure that both sides resolve the styles and components despite of the client path ending with fragment identifiers such as `#overview`. What do you think? Maybe we should wait for any advice from the maintainers?

**Comment by JeelRajodiya** [comment] 2024-03-04 10:09
Hello @benjagm,

I've found a solution to resolve the hydration errors. Please take a look at [this branch](https://github.com/JeelRajodiya/JSON-Schema-website/tree/hydration-fix) and give a feedback. 

@vishisht-dubey if the fix is accepted by the maintainers, please feel free to use it and open a PR

**Comment by benjagm** [comment] 2024-03-04 10:17
Thanks a lot for working on this. If that works please share the solution here. Thanks!!!

**Comment by JeelRajodiya** [comment] 2024-03-04 11:37
Sure!

# Solution 

## 1. Replace  `router.asPath` with `pathname` fetched through `usePathname()` from following files 
- `components/Sidebar.tsx` ( from line 139 to 150 ) ( see this [commit](https://github.com/JeelRajodiya/JSON-Schema-website/commit/544d30af3b5bd3ac8915ad1edad9729744b2d80b) )
- `components/Layout.tsx` ( line 120 ) ( see this [commit](https://github.com/JeelRajodiya/JSON-Schema-website/commit/916db4abab8def930b7d93bf22f18584852293ec) )

## Example 

![image](https://github.com/json-schema-org/website/assets/63534268/5fff09be-bce3-4877-bd73-b929106e62bd)
> I found the solution [here](https://stackoverflow.com/questions/75915658/how-to-access-router-aspath-in-a-function-that-uses-next-navigation-in-the-next)
## 2. Polyfill useLayoutEffect for SSR in JsonEditor
- The component that shows code snippets on the site uses slate library. However, slate is not optimized for SSR. 
### To resolve this, We can add the following code to our `components/JsonEditor.tsx`  ( See this [commit](https://github.com/JeelRajodiya/JSON-Schema-website/commit/c2a5716033f35910963f458f2fd7b8720617be05) )

### Code to add in  `components/JsonEditor.tsx` 
![image](https://github.com/json-schema-org/website/assets/63534268/9279f093-eecf-4cbc-aa7f-27945abf4b31)
> I found the solution [here](https://github.com/ianstormtaylor/slate/issues/3163) 
 
## 3. Use custom function to extract slug from child instead of RegEx
- in the `lib/slugifyMarkdownHeadline.ts` file, we are extracting the slug ( i.e id of the element ) using regEx. However, the regEx seem to generate different outputs in server and client (I do not know the cause). So, the trick is to use different method to extract id ( i.e. custom function ) 
- I think this fix is not that optimal, finding the cause of different outputs in regEx would be a better fix. 
- see this [commit](https://github.com/JeelRajodiya/JSON-Schema-website/commit/9990c6cbd72bf8dbc60a5f92169a8fd4b75b99d5)

### Custom Function
![image](https://github.com/json-schema-org/website/assets/63534268/2da59d34-0cd8-4277-8943-5f7e274897a0)

### Using The Function
![image](https://github.com/json-schema-org/website/assets/63534268/c1cd85c6-4666-4fe9-82b2-8cccd951ac6b)

@vishisht-dubey Hope you find it helpful

**Comment by benjagm** [comment] 2024-03-04 11:49
> Solution

@JeelRajodiya this is indeed a great job! Thanks a lot! Please join me as reviewer of the PR as soon as @vishisht-dubey analyze your proposal and proceed with these or other changes.

**Comment by vishisht-dubey** [comment] 2024-03-04 12:05
> > Solution
> 
> @JeelRajodiya this is indeed a great job! Thanks a lot! Please join me as reviewer of the PR as soon as @vishisht-dubey analyze your proposal and proceed with these or other changes.

Hiii @benjagm @JeelRajodiya i am proceeding with the changes thanks for helping will raise a pr by today after testing

**Comment by DarhkVoyd** [comment] 2024-03-04 13:05
@JeelRajodiya @benjagm I have some thoughts regarding our current approach:

- Since we're using the `Pages Router` across our project, let's stick with `useRouter` instead of introducing `usePathname` (which is better aligned with the `App Router`), using `usePathname` with the `Pages Router` might lead to unreliable behavior.

- The logic introduced in #304 depends on the `slugifyMarkdownHeadline` method. If we need to modify this method, let's coordinate with the #304 PR author to make sure everything stays compatible.

> The component that shows code snippets on the site uses slate library. However, slate is not optimized for SSR.

- Could you clarify why you believe the Slate component is causing the error, since my understanding is that code snippet rendering and our hydration issues should be separate issues?

**Comment by DarhkVoyd** [comment] 2024-03-04 13:15
@vishisht-dubey @DhairyaMajmudar I have a potential solution for our hydration issues. Here's my idea:

We might be able to achieve this by primarily relying on the `server-side pathname` which never contains fragment identifiers(such as`#overview`) to eliminate the discrepancies between server and client rendering which is due to `#<fragment-identiferes>` in the client side pathname. To make sure let's try always removing pathname after `#` to ensure consistency in the `slug` and `pathname` values used for `classes` and `conditional components`. What do you think?

**Comment by benjagm** [comment] 2024-03-04 13:28
I do like a lot what is happening in this issue with the healthy discussion. @DarhkVoyd @vishisht-dubey @DhairyaMajmudar @JeelRajodiya . Let me know when you get an agreement on the solution.

**Comment by DarhkVoyd** [comment] 2024-03-05 07:39
@JeelRajodiya 
> However, when I tested it, the output in the server and client is exactly the same.

It might be working. But since we are unaware of the underlying architecture and implementation of both the routers and hooks, I believe it would be unreliable and might fail at certain unexpected cases which we can't foresee. Instead, I agree we should rather find out a concrete solution rather than a bandaid fix. What do you think about my suggestion https://github.com/json-schema-org/website/issues/389#issuecomment-1976558029

> The changes I suggested above were to just substitute the regular expression with a custom function. So, my assumption is that it will have zero side effects on the output of the function itself.

In that case, I am not sure that would fix our error because we'll still end up with pathname discrepancies between server and the client.

> Yes, They are separate issues. However, I am leaving the details of the warning. In case, someone wants to open a new issue.

Since, you have a better understanding for the warning issue, can you please go ahead and create the issue for triage?

**Comment by benjagm** [comment] 2024-03-05 23:56
@DarhkVoyd Have you tested your proposal? https://github.com/json-schema-org/website/issues/389#issuecomment-1976558029

Sound like a clean solution. Is it affecting the url formats in some way?

**Comment by DarhkVoyd** [comment] 2024-03-06 04:45
@benjagm Yes, I've tested my solution and it works as intended. I haven't observed any negative impacts on the URL formats. Would you like me to create a draft PR to illustrate the implementation? Please let me know.

**Comment by DarhkVoyd** [comment] 2024-03-06 04:54
@benjagm Meanwhile, I just discovered that there's another hydration error originating from what seems the `StyledMarkdown` component which seems not related to pathname discrepancies but instead our custom markdown components. Would you rather have it solved here with this issue or create a separate issue. Lastly, it would be great if someone could help me pin point this new issue.

<img width="664" alt="Screenshot 2024-03-06 at 10 19 13 AM (2)" src="https://github.com/json-schema-org/website/assets/77478658/2493f705-764a-4384-ab1a-cf48bdc148ce">

**Comment by JeelRajodiya** [comment] 2024-03-06 05:05
@DarhkVoyd 
> It might be working. But since we are unaware of the underlying architecture and implementation of both the routers and hooks, I believe it would be unreliable and might fail at certain unexpected cases which we can't foresee. Instead, I agree we should rather find out a concrete solution rather than a bandaid fix. What do you think about my suggestion https://github.com/json-schema-org/website/issues/389#issuecomment-1976558029

If your solution works, then it is better the bandaid fix. I think we should go ahead with your solution. 

> In that case, I am not sure that would fix our error because we'll still end up with pathname discrepancies between server and the client.


One of the cause of the hydration error was, different slug names generated by the `slugifyMarkdownHeadline` function 
( The error you just mentioned in [this comment](https://github.com/json-schema-org/website/issues/389#issuecomment-1980086927) ) 

## Line 44, slug is generated by `slugifyMarkdownHeadline`  and slug is passed to id. hence id did not match error ( Server: "intro" Client: "introduction-to-json-schema" ) 
![image](https://github.com/json-schema-org/website/assets/63534268/42daf04d-7478-4105-9fd2-24c778e97710)


## The reason behind this error is, different output (  in server and client )  from `FRAGMENT_REGEX.exec(child)` ( line 14 ) function. 

![image](https://github.com/json-schema-org/website/assets/63534268/d7d5ae92-3822-4cca-aa07-b9d24b3da6f0)

# To resolve this check 3rd solution of my [previous comment](https://github.com/json-schema-org/website/issues/389#issuecomment-1976384784)

**Comment by DarhkVoyd** [comment] 2024-03-06 07:53
@JeelRajodiya Thank you so much for your help in pin pointing the markdown error. 

> Please check 3rd solution of my https://github.com/json-schema-org/website/issues/389#issuecomment-1976384784
>> I think this fix is not that optimal, finding the cause of different outputs in regEx would be a better fix.

Sure, we should probably find and fix the underlying cause.

**Comment by DarhkVoyd** [comment] 2024-03-06 08:23
@benjagm Could you please tell us which is the desired slug. Slug generated from the headline itself or the `[#<>]` after the headline i.e. from `Create a schema definition[#create]` do we want the slug as `create-a-schema-definition` or the as `create`

**Comment by DarhkVoyd** [comment] 2024-03-06 08:34
> Sure, we should probably find and fix the underlying cause.

Upon investigation, it appears the `FRAGMENT_REGEX` when used as a global variable instead of a local variable inside of the `slugifyMarkdownHeadline` is causing this error.

**Comment by JeelRajodiya** [comment] 2024-03-06 08:53
@DarhkVoyd 

The issue you're facing with the `FRAGMENT_REGEX` global variable is likely due to the way regular expressions are handled in JavaScript when used with the global (`g`) flag.

In JavaScript, when you use a regular expression with the global flag, it maintains a "lastIndex" property, which keeps track of the position in the string where the last match occurred. This property is modified as the regular expression is used to find subsequent matches, and it's not automatically reset between different uses of the same regular expression object.

When you define the `FRAGMENT_REGEX` as a global variable, it's shared across all instances of the `slugifyMarkdownHeadline` method invocations, and the lastIndex property might not be reset to 0 as expected. This can lead to unexpected behavior, especially if the method is called multiple times or in different contexts.

By moving the `FRAGMENT_REGEX` inside the `slugifyMarkdownHeadline` method, you're creating a new instance of the regular expression object each time the method is called, effectively resetting the lastIndex property to 0, and avoiding any potential conflicts or unexpected behavior caused by the global state.


**On a side note:** If you remove the `g` flag ( just for testing purpose ) from the regular expression.  The error is gone.

**Comment by DarhkVoyd** [comment] 2024-03-06 09:08
@JeelRajodiya Great! Thank you so much for helping out on this one. What do you suggest should be the best solution, should we just remove the `/g` flag or instead move the regex inside the method to ensure a clean copy is used each time. You did a pretty amazing job too. Great work by everyone!

**Comment by DarhkVoyd** [comment] 2024-03-06 09:18
> Let me know when you get an agreement on the solution
@benjagm  We have made some progress here, please let us know what do you think.

**Comment by benjagm** [comment] 2024-03-06 09:24
Good job everyone @DarhkVoyd @JeelRajodiya ! Let's add the solution to the PR.

**Comment by DarhkVoyd** [comment] 2024-03-06 09:29
@benjagm Hey, there is no PR linked to this issue. What do you suggest we do? Should I create a PR from my commit changes or should we wait for the assignee to implement the solution and create their PR?

**Comment by JeelRajodiya** [comment] 2024-03-06 09:34
> @JeelRajodiya Great! Thank you so much for helping out on this one. What do you suggest should be the best solution, should we just remove the `/g` flag or instead move the regex inside the method to ensure a clean copy is used each time. Currently, in my copy I am aligned to use the later. Meanwhile, let's should test if any other hydration errors are present to ensure that we have fixed any and all hydration errors. You did a pretty amazing job too. Amazing collaboration by everyone here!

I suggest we should move the regex inside the method.

**Comment by benjagm** [comment] 2024-03-06 09:46
As soon as you are aligned with the solution please submit a PR. I added @DarhkVoyd and @JeelRajodiya to the assignees of this issue so whatever you decided, please make sure we have a linked PR.

**Comment by DarhkVoyd** [comment] 2024-03-06 10:00
Sure, I have checked the website for other hydration errors and couldn't find any. @JeelRajodiya Please go ahead and link a PR.

**Closed** 2024-03-06 14:18 UTC
Labels: 🐛 Bug, Priority: Critical, Status: In Progress
