### ISSUE TITLE
🐛 Bug: Hydration Error

### ISSUE THREAD

**Issue by AdityaSingh-02** [json-schema-org/website#487] opened 2024-03-09 04:26 UTC
### Describe the bug

Go to http://localhost:3000/draft/2020-12/release-notes and you'll find a Hydration error

### Steps To Reproduce

1. Go to http://localhost:3000/draft/2020-12/release-notes
2. You will see the toast for hydration error

### Expected Behavior

There Should not be any kind of hydration error

### Screenshots

![Screenshot 2024-03-09 at 9 48 43 AM](https://github.com/json-schema-org/website/assets/94185167/253c96a3-600d-47e3-b991-e66f349571a4)

### Device Information [optional]

```markdown
- OS: Mac
- Browser: Chrome
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by benjagm** [comment] 2024-03-09 12:03
Are you checking the main branch? @DarhkVoyd @JeelRajodiya @vishisht-dubey Is this a different error than the one we fixed?

**Comment by JeelRajodiya** [comment] 2024-03-09 12:59
> Are you checking the main branch? @DarhkVoyd @JeelRajodiya @vishisht-dubey Is this a different error than the one we fixed?

Yes, this error is different. the problem seem to be in the `componenets/StyledMarkdown.tsx` file 

@AdityaSingh-02 You can solve this error by adding `<tbody>` tags inside each `<table>` element ( in the `pages\draft\2020-12\release-notes.md` file )

## Example: Line 39 and 66 have been added. 
<img src="https://github.com/json-schema-org/website/assets/63534268/db227e40-9859-470b-8f4c-93d0fb2cc9c4" width="50%"/>


Check [this](https://github.com/JeelRajodiya/JSON-Schema-website/commit/329c4896c65ba026ae6ca940b163e80bfa30f600) commit for more information

**Comment by DarhkVoyd** [comment] 2024-03-09 15:12
> Are you checking the main branch? @DarhkVoyd @JeelRajodiya @vishisht-dubey Is this a different error than the one we fixed?

Yes, I can reproduce this. This is a different hydration error from the one we recently fixed. This seems to be originating from the drafts data, unlike the one we fixed which was caused by fragment identifiers.

**Comment by AdityaSingh-02** [comment] 2024-03-09 15:14
@benjagm Could you please assign me this issue?

**Comment by AdityaSingh-02** [comment] 2024-03-10 04:43
Heyy @benjagm I have fixed this issue while working on another related issue, #483 which included release-notes.md 🚀

**Comment by benjagm** [comment] 2024-03-11 09:55
Thanks everyone. If AdityaSingh fixed it we'll close this as completed. Thanks.

**Closed by benjagm** 2024-03-11 09:55 UTC
Labels: 🐛 Bug, Status: Triage
