### ISSUE TITLE
Drop numbering in sample

### ISSUE THREAD

**Issue by LasneF** [json-schema-org/website#259] opened 2023-12-13 11:35 UTC
#### Description

Disable the numbering feature in the Javascript component show casing code like here 

![image](https://github.com/json-schema-org/website/assets/12461661/86eb7b49-4b91-42ed-9e6c-22d9f63012b0)

this is preventing to do cut copy , and does not bring so munch value

**Comment by gregsdennis** [comment] 2023-12-13 11:48
Duplicate of #214.

**Closed** 2023-12-13 11:48 UTC
Labels: enhancement
